==> /tmp/serial_mft03_out <==
Lustre: DEBUG MARKER: only running test 0b
Lustre: DEBUG MARKER: excepting tests:
Lustre: DEBUG MARKER: Using TIMEOUT=20
Lustre: 2196:0:(quota_master.c:793:close_quota_files()) quota[0] is off already
Lustre: 2196:0:(quota_master.c:793:close_quota_files()) Skipped 1 previous similar message
LustreError: 5280:0:(quota_ctl.c:328:client_quota_ctl()) ptlrpc_queue_wait failed, rc: -114
Lustre: 5334:0:(debug.c:326:libcfs_debug_str2mask()) You are trying to use a numerical value for the mask - this will be deprecated in a future release.
Lustre: 5334:0:(debug.c:326:libcfs_debug_str2mask()) Skipped 3 previous similar messages
Lustre: DEBUG MARKER: == replay-ost-single test 0b: empty replay == 17:50:15 (1333464615)
Lustre: Failing over lustre-OST0000
Lustre: lustre-OST0000: shutting down for failover; client state will be preserved.
Lustre: OST lustre-OST0000 has stopped.
LustreError: 2281:0:(ldlm_lib.c:2125:target_send_reply_msg()) @@@ processing error (-107)  req@ffff88007c0ca800 x1398238915592366/t0(0) o400-><?>@<?>:0/0 lens 192/0 e 0 to 0 dl 1333464626 ref 1 fl Interpret:H/0/ffffffff rc -107/-1
LustreError: 11-0: an error occurred while communicating with 0@lo. The obd_ping operation failed with -107
Lustre: lustre-OST0000-osc-ffff880037540800: Connection to service lustre-OST0000 via nid 0@lo was lost; in progress operations using this service will wait for recovery to complete.
Lustre: lustre-OST0000-osc-MDT0000: Connection to service lustre-OST0000 via nid 0@lo was lost; in progress operations using this service will wait for recovery to complete.
LustreError: 137-5: UUID 'lustre-OST0000_UUID' is not available  for connect (no target)
LustreError: 137-5: UUID 'lustre-OST0000_UUID' is not available  for connect (no target)
Lustre: server umount lustre-OST0000 complete
Lustre: 1609:0:(import.c:526:import_select_connection()) lustre-OST0000-osc-MDT0000: tried all connections, increasing latency to 6s
LustreError: 137-5: UUID 'lustre-OST0000_UUID' is not available  for connect (no target)
LustreError: 2281:0:(ldlm_lib.c:2125:target_send_reply_msg()) @@@ processing error (-19)  req@ffff880078f8a850 x1398238915592377/t0(0) o8-><?>@<?>:0/0 lens 368/0 e 0 to 0 dl 1333464650 ref 1 fl Interpret:/0/ffffffff rc -19/-1
LustreError: 2281:0:(ldlm_lib.c:2125:target_send_reply_msg()) Skipped 3 previous similar messages
Lustre: lustre-OST0001: haven't heard from client 048dfb9f-2515-148b-7b00-5707b563f1c7 (at 0@lo) in 48 seconds. I think it's dead, and I am evicting it. exp ffff880077258400, cur 1333464630 expire 1333464600 last 1333464582
LustreError: 11-0: an error occurred while communicating with 0@lo. The ost_connect operation failed with -19
LustreError: Skipped 3 previous similar messages
LDISKFS-fs (loop1): mounted filesystem with ordered data mode
LDISKFS-fs (loop1): mounted filesystem with ordered data mode
Lustre: 5682:0:(ldlm_lib.c:1900:target_recovery_init()) RECOVERY: service lustre-OST0000, 3 recoverable clients, last_transno 0
LustreError: 5683:0:(ldlm_lib.c:1737:target_recovery_thread()) lustre-OST0000: started recovery thread pid 5683
Lustre: 5682:0:(filter.c:1252:filter_prep_groups()) lustre-OST0000: initialize groups [0,0]
Lustre: lustre-OST0000: Now serving lustre-OST0000 on /dev/loop1 with recovery enabled
Lustre: lustre-OST0000: Will be in recovery for at least 1:00, or until 3 clients reconnect
LustreError: 5672:0:(obd_class.h:1622:obd_notify()) obd lustre-OST0000 has no notify handler
Lustre: 5708:0:(debug.c:326:libcfs_debug_str2mask()) You are trying to use a numerical value for the mask - this will be deprecated in a future release.
Lustre: 5708:0:(debug.c:326:libcfs_debug_str2mask()) Skipped 1 previous similar message
Lustre: 1609:0:(import.c:526:import_select_connection()) lustre-OST0000-osc-MDT0000: tried all connections, increasing latency to 11s
Lustre: 1609:0:(import.c:526:import_select_connection()) Skipped 1 previous similar message
Lustre: 2281:0:(ldlm_lib.c:873:target_handle_connect()) lustre-OST0000: connection from lustre-MDT0000-mdtlov_UUID@0@lo recovering/t0 exp ffff880037a9bc00 cur 1333464635 last 1333464631
Lustre: 2281:0:(filter.c:2710:filter_connect_internal()) lustre-OST0000: Received MDS connection for group 0
Lustre: 2281:0:(sec.c:1474:sptlrpc_import_sec_adapt()) import lustre-OST0000->NET_0x9000000000000_UUID netid 90000: select flavor null
Lustre: 1609:0:(import.c:526:import_select_connection()) lustre-OST0000-osc-ffff880037540800: tried all connections, increasing latency to 15s
Lustre: 5683:0:(ldlm_lib.c:1566:target_recovery_overseer()) recovery is timed out, evict stale exports
LustreError: 5683:0:(genops.c:1273:class_disconnect_stale_exports()) lustre-OST0000: disconnect stale client 048dfb9f-2515-148b-7b00-5707b563f1c7@<unknown>
Lustre: lustre-OST0000-osc-MDT0000: Connection restored to service lustre-OST0000 using nid 0@lo.
Lustre: lustre-OST0000: sending delayed replies to recovered clients
Lustre: lustre-OST0000-osc-ffff880037540800: Connection restored to service lustre-OST0000 using nid 0@lo.
Lustre: lustre-OST0000: received MDS connection from 0@lo
Lustre: MDS mdd_obd-lustre-MDT0000: lustre-OST0000_UUID now active, resetting orphans
Lustre: DEBUG MARKER: == replay-ost-single replay-ost-single.sh test complete, duration 88 sec == 17:51:41 (1333464701)
